import Link from "next/link";

const leads=[
 ["Lucía Serrano","Particular","Kia Sportage","Nuevo","Hoy · 09:42"],
 ["Antonio Marín","Autónomo","CUPRA Formentor","Contactado","Hoy · 08:15"],
 ["Grupo Nexo SL","Empresa","3 vehículos","Propuesta","Ayer · 17:30"],
 ["Miguel Rojas","Particular","Peugeot 2008","Documentación","Ayer · 12:04"],
];
export default function Control(){return <main className="control-page"><div className="control-shell"><aside className="control-side"><div className="brand inverse">PRISMA<span>CONTROL</span></div><nav><span className="active">Resumen</span><span>Leads</span><span>Ofertas</span><span>Clientes</span><span>Empresas</span><span>Analytics</span><Link href="/">← Ver web</Link></nav></aside><section className="control-main"><div className="control-head"><div><h1>Buenos días.</h1><p>Esto es lo que está pasando en PRISMA hoy.</p></div><span className="control-button">+ Nueva oferta</span></div><div className="metric-grid"><article className="metric"><span>Leads nuevos</span><strong>18</strong></article><article className="metric"><span>Por contactar</span><strong>7</strong></article><article className="metric"><span>Propuestas activas</span><strong>24</strong></article><article className="metric"><span>Conversión 30d</span><strong>14,8%</strong></article></div><div className="control-section"><div className="control-section-head"><h2>Últimos leads</h2><a>Ver todos →</a></div><table className="lead-table"><thead><tr><th>Cliente</th><th>Perfil</th><th>Interés</th><th>Estado</th><th>Entrada</th></tr></thead><tbody>{leads.map(l=><tr key={l[0]}><td className="lead-name">{l[0]}</td><td>{l[1]}</td><td>{l[2]}</td><td><span className="pill">{l[3]}</span></td><td>{l[4]}</td></tr>)}</tbody></table></div><div className="control-section"><div className="control-section-head"><h2>Pipeline comercial</h2><a>Pipeline completo →</a></div><div className="pipeline"><div className="pipeline-col"><span>Nuevo · 7</span><div className="mini-lead">Lucía Serrano<br/>310–450 €/mes</div></div><div className="pipeline-col"><span>Contactado · 11</span><div className="mini-lead">Antonio Marín<br/>CUPRA Formentor</div></div><div className="pipeline-col"><span>Propuesta · 9</span><div className="mini-lead">Grupo Nexo SL<br/>3 vehículos</div></div><div className="pipeline-col"><span>Documentación · 4</span><div className="mini-lead">Miguel Rojas<br/>Peugeot 2008</div></div></div></div></section></div></main>}
